### ISSUE TITLE
incorrect  sentence_bleu score for word  having length<3

### ISSUE THREAD

**Issue by Interioamar** [odashi/nmtkit#16]
I see incorrect bleu score  for the word length<3
ex:
from nltk.translate.bleu_score import sentence_bleu,corpus_bleu
reference = ['ant']
candidate = 'ant'
score = sentence_bleu(reference, candidate)
print(score)

####  1.2213386697554703e-77

However the same will work if I increased the length > 3.
So is the above known constraint for calculating bleu score?

**Comment by odashi** [comment]
@Interioamar Thanks, but is this a correct place to report this issue? It looks the issue is related to the NLTK toolkit.

IMO the BLEU-4 score with less than 4 words is basically meaningless because it requires at least 4-gram statistics. Toolkits usually implement some workaround to avoid exceptions, but it should be implementation-dependent.

**Comment by Interioamar** [comment]
Thanks got it
